# -*- coding: utf-8 -*-
"""AQI_RL_Traffic_Control_Assignment_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WyfzXTDnF107zVFXjnkbleZagFAcduVt
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files

uploaded = files.upload()

import os

print("Files in current folder:")
print(os.listdir())

from google.colab import files
import pandas as pd

# Upload file
uploaded = files.upload()

# Automatically read the uploaded CSV
filename = list(uploaded.keys())[0]

df = pd.read_csv(filename)

print("Dataset Loaded Successfully")
print("Filename:", filename)
print("Dataset Shape:", df.shape)

df.head()

def aqi_state(aqi):
    if aqi <= 100:
        return "Low AQI"
    elif aqi <= 200:
        return "Medium AQI"
    else:
        return "High AQI"

df['AQI_State'] = df['AQI'].apply(aqi_state)

df[['AQI', 'AQI_State']].head()

state_mapping = {
    "Low AQI":0,
    "Medium AQI":1,
    "High AQI":2
}

df['State'] = df['AQI_State'].map(state_mapping)

df[['AQI_State','State']].head()

actions = {
    0:"No Restriction",
    1:"Partial Restriction",
    2:"High-Pollution Alert"
}

print(actions)

reward_table = np.array([
    [10, -2, -5],   # Low AQI
    [-6, 10, 2],    # Medium AQI
    [-10, -3, 10]   # High AQI
])

reward_table

num_states = 3
num_actions = 3

Q = np.zeros((num_states, num_actions))

print(Q)

alpha = 0.1
gamma = 0.9
epsilon = 0.1
episodes = 500

rewards_per_episode = []

for episode in range(episodes):

    total_reward = 0

    for state in df['State']:

        if np.random.uniform(0,1) < epsilon:
            action = np.random.randint(num_actions)
        else:
            action = np.argmax(Q[state])

        reward = reward_table[state, action]

        next_state = state

        Q[state, action] = Q[state, action] + alpha * (
            reward + gamma * np.max(Q[next_state]) - Q[state, action]
        )

        total_reward += reward

    rewards_per_episode.append(total_reward)

print("Training Completed")

q_table = pd.DataFrame(
    Q,
    columns=[
        "No Restriction",
        "Partial Restriction",
        "High-Pollution Alert"
    ],
    index=[
        "Low AQI",
        "Medium AQI",
        "High AQI"
    ]
)

q_table

best_actions = np.argmax(Q, axis=1)

states = ["Low AQI","Medium AQI","High AQI"]

print("Final Learned Policy\n")

for i, state in enumerate(states):
    print(state, "->", actions[best_actions[i]])

average_reward = np.mean(rewards_per_episode)

print("Average Reward After Training:", round(average_reward,2))

plt.figure(figsize=(10,5))
plt.plot(rewards_per_episode)
plt.title("Reward per Episode")
plt.xlabel("Episode")
plt.ylabel("Total Reward")
plt.grid(True)
plt.show()

plt.figure(figsize=(8,4))

plt.imshow(Q, cmap='YlGnBu')

plt.colorbar()

plt.xticks(
    [0,1,2],
    ["No Restriction","Partial Restriction","High Alert"]
)

plt.yticks(
    [0,1,2],
    ["Low AQI","Medium AQI","High AQI"]
)

plt.title("Q-Table Heatmap")

plt.show()

action_counts = np.bincount(best_actions)

plt.figure(figsize=(6,4))

plt.bar(
    ["No Restriction","Partial Restriction","High Alert"],
    action_counts
)

plt.title("Action Distribution")

plt.ylabel("Count")

plt.show()